# Generated by Django 6.0.1 on 2026-01-16 22:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneycheckerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_index', models.PositiveSmallIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='honeychecker_record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoneywordSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.PositiveSmallIntegerField(default=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('algorithm_version', models.CharField(default='v1', max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='honeyword_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoneywordHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('password_hash', models.CharField(max_length=256)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashes', to='django_honeywords.honeywordset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('set', 'index'), name='uniq_honeywordhash_set_index')],
            },
        ),
    ]
