# Generated by Django 6.0.1 on 2026-02-12 11:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmnesiaSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.PositiveSmallIntegerField(default=20)),
                ('p_mark', models.FloatField(default=0.1)),
                ('p_remark', models.FloatField(default=0.01)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('algorithm_version', models.CharField(default='amnesia_v1', max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amnesia_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoneywordEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('outcome', models.CharField(choices=[('real', 'Real password'), ('honey', 'Honeyword'), ('invalid', 'Invalid')], max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoneywordUserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_reset', models.BooleanField(default=False)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('lock_count', models.PositiveIntegerField(default=0)),
                ('last_lock_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='honeywords_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AmnesiaCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('password_hash', models.CharField(max_length=256)),
                ('marked', models.BooleanField(default=False)),
                ('aset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='django_honeywords.amnesiaset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('aset', 'index'), name='uniq_amnesia_cred_aset_index')],
            },
        ),
    ]
