# Generated by Django 6.1.1 on 2026-09-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_honeywords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honeywordevent',
            name='outcome',
            field=models.CharField(choices=[('real', 'Marked credential'), ('honey', 'Honeyword'), ('invalid', 'Invalid')], max_length=16),
        ),
    ]
